ifeq ($(filter m y, $(CONFIG_TOUCHSCREEN_FOCALTECH_MMI)),)
obj-m := focaltech_mmi.o
endif

focaltech_mmi-objs += focaltech_ts.o
focaltech_mmi-objs += focaltech_flash.o
focaltech_mmi-objs += focaltech_upgrade_ft8716.o
focaltech_mmi-objs += focaltech_upgrade_idc.o
focaltech_mmi-objs += focaltech_upgrade_ft5x46.o
focaltech_mmi-objs += focaltech_upgrade_ft5422u.o
focaltech_mmi-objs += focaltech_upgrade_ft8006u.o
